version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
#  AfterInstall:
#    - location: scripts/stop.sh
#      timeout: 60
#      runas: ubuntu
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180
      runas: ubuntu
#    - location: scripts/health_check.sh
#      timeout: 180
#      runas: ubuntu
    - location: scripts/switch.sh
      timeout: 180
      runas: ubuntu
#    - location: scripts/start.sh
#      timeout: 60
#      runas: ubuntu


