cloud:
  aws:
    credentials:
      secret-key: EKu4jABYSRZ7iZj/83AOmimsDAab162Ma/5gS5I1
      access-key: AKIAY26BJCHR2ZJUOWGX
    s3:
      bucket: s3bbbb
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'

logging:
  level:
    org:
      apache:
        coyote:
          http11: ERROR
    com:
      example: ERROR

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include: secret
  datasource:
    password: ''
    username: ''
    url: ''
  jpa:
    hibernate:
      ddl-auto: ''
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jwt:
  secret:
    key: ''

