cloud:
  aws:
    credentials:
      secret-key: ''
      access-key: ''
    s3:
      bucket: ''
    region:
      static: ''
    stack:
      auto: 'false'

logging:
  level:
    org:
      apache:
        coyote:
          http11: ERROR
    com:
      example: debug

spring:
  # 네이버 관련
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:3000/user/signin/naver
            authorization-grant-type: authorization_code
            client-secret: ''
            scope: id,nickname,email,gender,age,profile_image
            client-id: ''
            client-name: Naver
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include: secret
  datasource:
    password: ''
    username: ''
    url: ''
  jpa:
    hibernate:
      ddl-auto: ''
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jwt:
  secret:
    key: ''

# 카카오 rest api key
kakao:
  rest:
    api:
      key: ''

# sentry
sentry:
  dsn: ''
